### ISSUE TITLE
Crash on app load on Android 15

### ISSUE THREAD

**Issue by jmc-figueira** [carrismetropolitana/android#2]
The app crashes moments after opening it, while hanging (I suspect) trying to load the map views for the line cards:

https://github.com/user-attachments/assets/3af67223-2654-4dee-ad01-b7d1693b2a6e

This started happening immediately after I updated my phone's (Google Pixel 7 Pro) OS to Android 15, which leads me to believe the crash is related to that Android version introducing some compatibility with the app (again, I suspect with the mapping library being used). I'm running the latest version of the app published on Google Play (2024.10.03).

If you need any further info from me to assist with debugging I'll be glad to provide it.

**Comment by jmc-figueira** [comment]
I got a bug report from the device's developer options and I found this peculiar section related to this crash:

```
10-19 03:02:01.179 10372 12460 12557 E AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
10-19 03:02:01.179 10372 12460 12557 E AndroidRuntime: Process: pt.carrismetropolitana.mobile, PID: 12460
10-19 03:02:01.179 10372 12460 12557 E AndroidRuntime: java.lang.OutOfMemoryError: Failed to allocate a 8208 byte allocation with 117376 free bytes and 114KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
10-19 03:02:01.179 10372 12460 12557 E AndroidRuntime: 	at okio.Segment.<init>(Segment.kt:62)
10-19 03:02:01.179 10372 12460 12557 E AndroidRuntime: 	at okio.SegmentPool.take(SegmentPool.kt:90)
10-19 03:02:01.179 10372 12460 12557 E AndroidRuntime: 	at okio.Buffer.writableSegment$okio(Buffer.kt:1490)
10-19 03:02:01.179 10372 12460 12557 E AndroidRuntime: 	at okio.InflaterSource.readOrInflate(InflaterSource.kt:72)
10-19 03:02:01.179 10372 12460 12557 E AndroidRuntime: 	at okio.InflaterSource.read(InflaterSource.kt:49)
10-19 03:02:01.179 10372 12460 12557 E AndroidRuntime: 	at okio.GzipSource.read(GzipSource.kt:69)
10-19 03:02:01.179 10372 12460 12557 E AndroidRuntime: 	at okio.RealBufferedSource.read(RealBufferedSource.kt:193)
10-19 03:02:01.179 10372 12460 12557 E AndroidRuntime: 	at okio.ForwardingSource.read(ForwardingSource.kt:27)
10-19 03:02:01.179 10372 12460 12557 E AndroidRuntime: 	at retrofit2.OkHttpCall$ExceptionCatchingResponseBody$1.read(OkHttpCall.java:317)
10-19 03:02:01.179 10372 12460 12557 E AndroidRuntime: 	at okio.Buffer.writeAll(Buffer.kt:1308)
10-19 03:02:01.179 10372 12460 12557 E AndroidRuntime: 	at okio.RealBufferedSource.readString(RealBufferedSource.kt:97)
10-19 03:02:01.179 10372 12460 12557 E AndroidRuntime: 	at okhttp3.ResponseBody.string(ResponseBody.kt:187)
10-19 03:02:01.179 10372 12460 12557 E AndroidRuntime: 	at retrofit2.converter.kotlinx.serialization.Serializer$FromString.fromResponseBody(Serializer.kt:25)
10-19 03:02:01.179 10372 12460 12557 E AndroidRuntime: 	at retrofit2.converter.kotlinx.serialization.DeserializationStrategyConverter.convert(DeserializationStrategyConverter.kt:11)
10-19 03:02:01.179 10372 12460 12557 E AndroidRuntime: 	at retrofit2.converter.kotlinx.serialization.DeserializationStrategyConverter.convert(DeserializationStrategyConverter.kt:7)
10-19 03:02:01.179 10372 12460 12557 E AndroidRuntime: 	at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:246)
10-19 03:02:01.179 10372 12460 12557 E AndroidRuntime: 	at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:156)
10-19 03:02:01.179 10372 12460 12557 E AndroidRuntime: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
10-19 03:02:01.179 10372 12460 12557 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
10-19 03:02:01.179 10372 12460 12557 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
10-19 03:02:01.179 10372 12460 12557 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
10-19 03:02:01.193  1000  1622  5316 W ActivityTaskManager:   Force finishing activity pt.carrismetropolitana.mobile/.MainActivity
```

It seems that the OkHttp library attempts to allocate memory on a loop until it runs out and crashes the application. I have looked at the library's repository and there seem to be no issues related to Android 15, so it's either unreported (unlikely) or related to the above-mentioned maps failing to load.

**Comment by ricardojorgerm** [comment]
Some of the calls are really large in terms of information (several MB). Maybe worth to consider android:largeHeap="true" if indeed this is not a loop, and instead simply too many calls containing lots of information (stops, lines, etc.)

**Comment by joao-vasconcelos** [comment]
A aplicação será atualizada em breve, totalmente rescrita.
